export const projects = [
  {
    id: 1,
    title: "AI-Based Fire Detection System",
    branch: "Computer Science / Electronics",
    description:
      "Utilizes AI-driven image processing to detect fire and smoke in real-time from CCTV feeds. Built using Python, TensorFlow, and OpenCV for automated fire detection.",
    technologyStack: ["Python", "TensorFlow", "OpenCV", "Machine Learning", "CCTV Integration"],
    objectives: [
      "Develop an AI-based system that detects fire and smoke in real-time.",
      "Reduce human dependency in fire detection.",
      "Implement a real-time alert system for fire incidents.",
    ],
    benefits: [
      "Improves safety by automating fire detection.",
      "Reduces response time in emergencies.",
      "Lower implementation costs compared to traditional systems.",
    ],
    challenges: [
      "Integrating real-time video processing with high accuracy.",
      "Maintaining robustness in diverse lighting conditions.",
      "Optimizing the model for faster detection on limited hardware.",
    ],
    futureGoal:
      "Integrate IoT sensors and develop a cloud-based alert system for large-scale deployment in industrial and residential buildings.",
    image: "https://th.bing.com/th/id/OIP.ng5ENi7AqsCASwqhe08ncQHaEO?cb=iwp2&rs=1&pid=ImgDetMain",
    date: "2024-03-10",
    pptLink: "/ppt/AI-Based-Fire-Detection.pptx",
    team: [
      {
        name: "Amit Kumar",
        role: "Project Lead",
        registrationNo: "CS123456",
        branch: "Computer Science",
        session: "2020-2024",
        linkedin: "https://www.linkedin.com/in/amitkumar",
        photo: "https://randomuser.me/api/portraits/men/1.jpg",
      },
      {
        name: "Fatima Begum",
        role: "AI Engineer",
        registrationNo: "CS123457",
        branch: "Computer Science",
        session: "2020-2024",
        linkedin: "https://www.linkedin.com/in/fatimabegum",
        photo: "https://randomuser.me/api/portraits/women/2.jpg",
      },
      {
        name: "Rahul Sharma",
        role: "Data Scientist",
        registrationNo: "CS123458",
        branch: "Computer Science",
        session: "2020-2024",
        linkedin: "https://www.linkedin.com/in/rahulsharma",
        photo: "https://randomuser.me/api/portraits/men/4.jpg",
      },
      {
        name: "Priya Singh",
        role: "Software Developer",
        registrationNo: "CS123459",
        branch: "Computer Science",
        session: "2020-2024",
        linkedin: "https://www.linkedin.com/in/priyasingh",
        photo: "https://randomuser.me/api/portraits/women/5.jpg",
      },
      {
        name: "Ankit Verma",
        role: "System Architect",
        registrationNo: "CS123460",
        branch: "Computer Science",
        session: "2020-2024",
        linkedin: "https://www.linkedin.com/in/ankitverma",
        photo: "https://randomuser.me/api/portraits/men/6.jpg",
      },
    ],
  },
  {
    id: 2,
    title: "Voice Controlled Wheelchair",
    branch: "Electronics / Biomedical / Robotics",
    description:
      "Design of a voice-controlled wheelchair to assist physically disabled individuals. Uses Arduino, Bluetooth, and speech recognition for hands-free mobility.",
    technologyStack: ["Arduino", "Bluetooth Module", "Speech Recognition", "Embedded Systems"],
    objectives: [
      "Enable wheelchair control via voice commands.",
      "Provide a cost-effective mobility solution.",
      "Assist differently-abled individuals with hands-free movement.",
    ],
    benefits: [
      "Enhances independence for users.",
      "Cost-effective compared to commercial systems.",
      "Easy-to-use for all age groups.",
    ],
    challenges: [
      "High accuracy in noisy environments.",
      "Power optimization in battery-operated systems.",
      "Stable communication between control module and wheelchair.",
    ],
    futureGoal:
      "Add GPS-based navigation and enhance voice recognition using AI for contextual understanding.",
    image:
      "https://i0.wp.com/techacute.com/wp-content/uploads/2017/09/Panasonic-Haneda-Whill-Next-Airport-Mobility-Support-Wheelchair-Robotic-Autonomous-Self-Driving-Tandem-Single-File-Navigation-App-Smartphone-Staff-Help.jpg?fit=800%2C480&ssl=1",
    date: "2024-04-25",
    pptLink: "/ppt/Voice-Controlled-Wheelchair.pptx",
    team: [
      {
        name: "Rajesh Patel",
        role: "Project Manager",
        registrationNo: "BM123456",
        branch: "Biomedical",
        session: "2020-2024",
        linkedin: "https://www.linkedin.com/in/rajeshpatel",
        photo: "https://randomuser.me/api/portraits/men/3.jpg",
      },
      {
        name: "Ayesha Khan",
        role: "Electrical Engineer",
        registrationNo: "EE123456",
        branch: "Electronics",
        session: "2020-2024",
        linkedin: "https://www.linkedin.com/in/ayeshakhan",
        photo: "https://randomuser.me/api/portraits/women/3.jpg",
      },
      {
        name: "Suresh Mehta",
        role: "Hardware Specialist",
        registrationNo: "EE123457",
        branch: "Electronics",
        session: "2020-2024",
        linkedin: "https://www.linkedin.com/in/sureshmehta",
        photo: "https://randomuser.me/api/portraits/men/7.jpg",
      },
      {
        name: "Neha Gupta",
        role: "Software Engineer",
        registrationNo: "BM123458",
        branch: "Biomedical",
        session: "2020-2024",
        linkedin: "https://www.linkedin.com/in/nehagupta",
        photo: "https://randomuser.me/api/portraits/women/8.jpg",
      },
      {
        name: "Vikram Singh",
        role: "Robotics Engineer",
        registrationNo: "BM123459",
        branch: "Biomedical",
        session: "2020-2024",
        linkedin: "https://www.linkedin.com/in/vikramsingh",
        photo: "https://randomuser.me/api/portraits/men/9.jpg",
      },
    ],
  },
  {
    id: 3,
    title: "Smart Irrigation System",
    branch: "Electronics / IoT",
    description:
      "An IoT-based smart irrigation system that monitors soil moisture and automates water supply to optimize water usage in agriculture.",
    technologyStack: ["IoT", "Arduino", "Sensors", "Cloud Integration"],
    objectives: [
      "Monitor soil moisture levels in real-time.",
      "Automate water supply based on soil conditions.",
      "Reduce water wastage in agriculture.",
    ],
    benefits: [
      "Improves crop yield by ensuring optimal water supply.",
      "Reduces water consumption and wastage.",
      "Provides remote monitoring and control for farmers.",
    ],
    challenges: [
      "Ensuring sensor accuracy in diverse soil conditions.",
      "Maintaining system reliability in outdoor environments.",
      "Integrating with cloud platforms for remote access.",
    ],
    futureGoal:
      "Expand the system to include weather forecasting and crop-specific irrigation recommendations.",
    image: "https://cdn.pixabay.com/photo/2017/01/20/00/30/sprinkler-1990927_960_720.jpg",
    date: "2024-05-15",
    pptLink: "/ppt/Smart-Irrigation-System.pptx",
    team: [
      {
        name: "Karan Malhotra",
        role: "IoT Specialist",
        registrationNo: "EE123460",
        branch: "Electronics",
        session: "2020-2024",
        linkedin: "https://www.linkedin.com/in/karanmalhotra",
        photo: "https://randomuser.me/api/portraits/men/10.jpg",
      },
      {
        name: "Pooja Sharma",
        role: "Agricultural Consultant",
        registrationNo: "AG123456",
        branch: "Agriculture",
        session: "2020-2024",
        linkedin: "https://www.linkedin.com/in/poojasharma",
        photo: "https://randomuser.me/api/portraits/women/11.jpg",
      },
      {
        name: "Ravi Kumar",
        role: "Embedded Systems Engineer",
        registrationNo: "EE123461",
        branch: "Electronics",
        session: "2020-2024",
        linkedin: "https://www.linkedin.com/in/ravikumar",
        photo: "https://randomuser.me/api/portraits/men/12.jpg",
      },
      {
        name: "Anjali Verma",
        role: "Cloud Engineer",
        registrationNo: "CS123461",
        branch: "Computer Science",
        session: "2020-2024",
        linkedin: "https://www.linkedin.com/in/anjaliverma",
        photo: "https://randomuser.me/api/portraits/women/13.jpg",
      },
      {
        name: "Mohit Jain",
        role: "System Integrator",
        registrationNo: "EE123462",
        branch: "Electronics",
        session: "2020-2024",
        linkedin: "https://www.linkedin.com/in/mohitjain",
        photo: "https://randomuser.me/api/portraits/men/14.jpg",
      },
    ],
  },

  // ...Keep the rest of the projects from 3 to 10 as-is following the same format...

  // Optionally add any new projects here in the same structure.
];

